# -*- coding: utf-8 -*-
"""DataTransform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10UWGHiY4WZyD5A1S3Gly-mPUEpjn3_Io
"""

from google.colab import files
import pandas as pd
import shutil
import os

uploaded = files.upload()

file_name = next(iter(uploaded))
target_path = '/content/bc_trip259172515_230215.csv'
shutil.move(file_name, target_path)

df = pd.read_csv(target_path)
print("Number of breadcrumb records:", len(df))
print(df.head())

drop_tables = df.drop(columns=['EVENT_NO_STOP', 'GPS_SATELLITES', 'GPS_HDOP'])
print(drop_tables.head())

filter = pd.read_csv(
    '/content/bc_trip259172515_230215.csv',
    usecols=lambda col: col not in ['EVENT_NO_STOP', 'GPS_SATELLITES', 'GPS_HDOP']
)

print(filter.head())

filter['OPD_DATE'] = pd.to_datetime(filter['OPD_DATE'], format='%d%b%Y:%H:%M:%S')

filter['ACT_TIME'] = pd.to_timedelta(filter['ACT_TIME'], unit='s')

filter['TIMESTAMP'] = filter['OPD_DATE'] + filter['ACT_TIME']

print(filter[['OPD_DATE', 'ACT_TIME', 'TIMESTAMP']].head())


print(filter.head())

filter = filter.drop(columns=['OPD_DATE', 'ACT_TIME'])

print(filter.head())

filter['dM'] = filter['METERS'].diff()
filter['dT'] = filter['TIMESTAMP'].diff().dt.total_seconds()

filter['SPEED'] = filter.apply(
    lambda row: row['dM'] / row['dT'] if row['dT'] and row['dT'] != 0 else 0,
    axis=1
)

filter.drop(columns=['dM', 'dT'], inplace=True)


print(f"Minimum Speed:",filter['SPEED'].min())
print(f"Maximum Speed:",filter['SPEED'].max())
print(f"Average Speed:",  filter['SPEED'].mean())

from google.colab import files
import pandas as pd

uploaded = files.upload()
large_df = pd.read_csv("bc_veh4223_230215.csv")

large_df['OPD_DATE'] = pd.to_datetime(large_df['OPD_DATE'], format='%d%b%Y:%H:%M:%S')

large_df['TIMESTAMP'] = large_df['OPD_DATE'] + pd.to_timedelta(large_df['ACT_TIME'], unit='s')

large_df['dM'] = large_df['METERS'].diff()
large_df['dT'] = large_df['TIMESTAMP'].diff()

large_df['SPEED'] = large_df.apply(
    lambda row: row['dM'] / row['dT'].total_seconds() if pd.notna(row['dT']) else None,
    axis=1
)

trip = large_df.groupby('EVENT_NO_TRIP')['SPEED'].agg(['max', 'median'])

max_speed = trip.loc[trip['max'].idxmax()]
speed_value = max_speed['max']

max_record = large_df[large_df['SPEED'] == speed_value].iloc[0]

print(f"Max speed for vehicle #4223 on Feb 15, 2023 was", max_speed)
print(f"The Location ,Longitude, Latitude and time of max speed:", max_record['GPS_LONGITUDE'], max_record['GPS_LATITUDE'], max_record['TIMESTAMP'])
print(f"Median speed for vehicle #4223 on February 15 2023: {trip['median'].median()} m/s")